name: asciidoctor-ghpages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# single message type
on:
  telegram_bot:
    event: text

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
    - name: asciidoctor-ghpages
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        asciidoctor_params: --attribute=nofooter
        pdf_build: true
        ebook_main_adoc_file: 'latest'
        post_build: 'asciidoctor latest.adoc -o index.html;touch index.html; pwd; ls -lrt; git add -f index.html'
    - name: Send telegram message - hackernews
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: latest.pdf
        message: |
                Welcome to telegram world!
                more features in pipeline, NLP, Resume Parser

