name: Build and Deploy Resumes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby and Asciidoctor
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Asciidoctor
        run: gem install asciidoctor

      - name: Build site
        run: |
          mkdir public
          echo '{"resumes":[' > public/resumes.json
          FIRST=true
          for f in tailored_resumes/*.adoc; do
            if [ "$FIRST" = false ]; then
              echo ',' >> public/resumes.json
            fi
            FILENAME=$(basename -- "$f")
            FILENAME_NOEXT="${FILENAME%.*}"
            TITLE=$(grep '^= ' "$f" | sed 's/^= //' | sed 's/\"/\"/g')
            HTML_FILE="$FILENAME_NOEXT.html"
            
            asciidoctor -D public -o $HTML_FILE $f -a stylesheet=themes/resume.css --attribute=nofooter
            
            printf '{"title":"%s", "url":"%s"}' "$TITLE" "$HTML_FILE" >> public/resumes.json
            FIRST=false
          done
          echo ']}' >> public/resumes.json
          
          cp dashboard.html public/index.html
          cp -r themes public/themes

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
